//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent_of_code_2023.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent_of_code_2023.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à six1mpffbnbnnlxthree
        ///4eight3one92
        ///9nine2xnhvjtjlzj48
        ///jxrbrt4jmnmlonesznvbjrsn
        ///nsvkljgpfn77pvfour5j
        ///fourlkgmnnzncht75
        ///shqmhnlbjjvskone6two78
        ///qjgcxccgthree85five
        ///eight7sbdbgqgcfive3two
        ///eight878nckqdt3pgzc
        ///pkdrhksqdhrvhg5
        ///nine7four7one2
        ///9fives
        ///fplzzhthreethree7sqnsmrljgsmnpktfkhzdpqfkone
        ///hqrcls33sevensevennine
        ///four4m
        ///seven331fivekfrqbd
        ///ninechvkpthreefive8tlmfclr
        ///8954bxsqntndjmonenx5
        ///nine7km
        ///seven588sevenxffivethreehkrczrlm
        ///3cmjzjmhone
        ///jfgr2fourtflvttr
        ///qpplcgvklzztqjkbbnfiveftcqmlrqnd824        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Game 1: 3 blue, 2 green, 6 red; 17 green, 4 red, 8 blue; 2 red, 1 green, 10 blue; 1 blue, 5 green
        ///Game 2: 9 red, 2 green; 5 red, 1 blue, 6 green; 3 green, 13 red, 1 blue; 3 red, 6 green; 1 blue, 14 red, 6 green
        ///Game 3: 6 red, 3 blue, 8 green; 6 blue, 12 green, 15 red; 3 blue, 18 green, 4 red
        ///Game 4: 1 blue, 4 red; 2 blue, 6 red; 13 blue; 11 blue, 1 green, 8 red; 10 blue, 3 green, 2 red; 3 green, 7 blue
        ///Game 5: 2 red, 1 blue, 8 green; 2 blue, 7 green, 3 red; 1 blue, 7 green, 4 red; 2 blue, 1 green, 1 red [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ....411...............838......721.....44..............................................607..................................................
        ///...&amp;......519..................*..........#.97.........994..............404..............*...&amp;43........440...882.......673.505.............
        ///.....*......*...892.........971...%....131....*..........*.......515...$.......157.....412.............-.....*.............*............594.
        ///..856.495....13...-...............602..........36...$.985....341*.........88.....*.921 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Card   1: 36 15 12 91 47 98 59 46 83 86 | 86 34 88  7 36 82 90 32 83 56 27 45 49 69 91 47 98 59 13 15 68 12 17 11 46
        ///Card   2: 55 82  6 50 62  4 21 96 14 39 | 11 34 14 52  7 28 13 81 10 98 88 48 21 22 96  1 93 83 85 60 76 87 57 56 62
        ///Card   3: 11 88 40  9  7 37 92 15 70 53 | 55 37 97 22 77 34 83 98  1 92 38  5 69 54 25 73 13 94 62 96 78 93 75 23 31
        ///Card   4: 83 15  5  4  3 92 86  2 91 58 | 58  2 77 32 93 64 37 82 47 28 13 89 16 24 59 76 52 50 55 15 14 68 61 91 98
        ///Card   5: 59 25  2 83 13 26 39 45 28 74 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seeds: 4043382508 113348245 3817519559 177922221 3613573568 7600537 773371046 400582097 2054637767 162982133 2246524522 153824596 1662955672 121419555 2473628355 846370595 1830497666 190544464 230006436 483872831
        ///
        ///seed-to-soil map:
        ///4064811 506246814 25615317
        ///1520011681 1661018909 106057083
        ///1007960598 8836276 47579700
        ///1055540298 679332386 82196064
        ///2377475243 3574057730 33434621
        ///2323567163 2090355001 53908080
        ///2724594670 4209189177 35645909
        ///3247614896 4244835086 50132210
        ///2793935335 3209861711 430023 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time:        42     89     91     89
        ///Distance:   308   1170   1291   1467.
        /// </summary>
        internal static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
    }
}
